stages:
  
  Training:
    cmd: python fraud_svm.py
    
    deps:
      - fraud_svm.py
      - Data/creditcard.csv
      

    outs:
      - Models/Fraud_SVM.pkl
      - Data/x_test.csv
      - Data/y_test.csv
    

   
  Testing:
    cmd: python fraud_svm_test.py 

    deps:
      - fraud_svm_test.py 
      - Data/x_test.csv
      - Data/y_test.csv
      - Models/Fraud_SVM.pkl
      
    outs:
      - auc.png
      - confusion_mat.png
<<<<<<< HEAD

    metrics:
=======
    plots:
>>>>>>> 40d4dba370072fdd54116a56192d991597e29516
      - Output/Accuracy.json:
          cache: false

<<<<<<< HEAD
              



=======
>>>>>>> 40d4dba370072fdd54116a56192d991597e29516

